### ISSUE TITLE
Still active, or accepting contributions?

### ISSUE THREAD

**Issue by boramalper** [puffinrocks/puffin#26]
Hello!

I was looking for a ["homebrew for servers"](https://www.reddit.com/r/selfhosted/comments/bm7bv6/homebrew_for_servers/) on reddit and someone suggested me puffin. I think the idea is great, but sadly the development seem to have stalled.

I would personally be happy to start contributing, fixing things, adding new packages, etc. if you are also OK with that. I just wanted know if you are open to new contributions/contributors.

Thanks for the good work!
Bora

**Comment by loomchild** [comment]
Hi, 

You are right that development has stalled and I am currently focusing on other projects. However I am still using Puffin for personal hosting so I am still interested in maintaining it. I also finally decided to keep using the same technology overall (Docker Compose) instead of doing a big rewrite (in Kubernetes for example). 

I'd be happy to review your contributions and accept the and restart a bit my personal involvement, if you find the project useful.
